version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "actions/*"
      github:
        patterns:
          - "github/*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      react:
        patterns:
          - "react"
          - "react-dom"
    # split constraints by SemVer granularity to be more aggressive with patches
    # but cautious with breaking changes.
    cooldown:
      default-days: 7
      semver-major-days: 14 # Wait 2 weeks for major versions
      semver-minor-days: 7  # Wait 1 week for features
      semver-patch-days: 2  # Wait 2 days for patches
