name: Relese gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/**"
      - "README.md"

concurrency: ci-${{ github.ref }}

jobs:
  gh-release:
    name: GitHub Pages Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Install Node Packages
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile --prefer-offline
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DOCUSAURUS_IGNORE_SSG_WARNINGS: true
        run: |
          git config --global user.email "sdelrio@users.noreply.github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn deploy
          else
            npm run deploy
          fi

