name: Relese gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      # - ".github/workflows/**"
      - "README.md"


permissions: # required by action JamesIves/github-pages-deploy-action
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  gh-release:
    name: GitHub Pages Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 23.x
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4

      # - name: Get opened PRs
      #   id: openedPRs
      #   env:
      #     GH_TOKEN: ${{ github.token }}
      #   run: |
      #     json_array="$(gh pr list --state open --json number --jq 'map("mypath/pr-\(.number)")' | tr -d '\n')
      #     echo "openprs=$json_array"" >> $GITHUB_OUTPUT
      #
      # - name: Info
      #   env:
      #    openprs: "${{ steps.openedPRs.outputs.openprs }}"
      #   run: |
      #     echo ${{ env.openprs }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: './yarn.lock'

      - name: Cache Node.js modules to speed up future builds
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: docusaurus-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            docusaurus-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Install Node Packages
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile --prefer-offline
          else
            exit 1
          fi

      - name: Build Docusaurus
        env:
          USE_SSH: true
          GIT_USER: git
          DOCUSAURUS_IGNORE_SSG_WARNINGS: true
          BASE_URL: ""
        run: |
          git config --global user.email "sdelrio@users.noreply.github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn build
          else
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          clean-exclude: |
            pr-preview/

#          clean-exclude: ${{ fromJson(steps.openedPRs.outputs.openprs) }}

