name: Relese gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      # - ".github/workflows/**"
      - "README.md"


permissions: # required by action JamesIves/github-pages-deploy-action
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  gh-release:
    name: GitHub Pages Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 23.x
    steps:
      - uses: actions/checkout@v4

      - name: Get opened PRs
        id: openedPRs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          openprs="$(gh pr list --state open --json number --template '{{range .}}pr-preview/pr-{{ .number}}{{"\n"}}{{end}}')"
          TEST="A super long multine string here
          Line 2
          Line 3
          "
          {
            echo 'prs<<EOF'
            echo "${openprs}"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Info
        env:
          openprs: "${{ steps.openedPRs.outputs.prs }}"
        run: |
          echo ${{ env.openprs }}

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: docusaurus-${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            docusaurus-${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: './yarn.lock'

      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}

      - name: Install Node Packages
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile --prefer-offline
          else
            exit 1
          fi

      - name: Build Docusaurus
        env:
          USE_SSH: true
          GIT_USER: git
          DOCUSAURUS_IGNORE_SSG_WARNINGS: true
          BASE_URL: ""
        run: |
          git config --global user.email "sdelrio@users.noreply.github.com"
          git config --global user.name "gh-actions"
          if [ -e yarn.lock ]; then
            yarn build
          else
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          clean-exclude: |
            ${{ steps.openedPRs.outputs.prs }}

